.readthedocs.yaml, README.md, changelog/16.docs.md, changelog/16.feature.md, conftest.py, packages/ref-core/src/ref_core/exceptions.py, packages/ref-core/src/ref_core/providers.py, packages/ref-core/tests/unit/test_providers.py, packages/ref/src/ref/cli/__init__.py, packages/ref/src/ref/cli/solve.py, packages/ref/src/ref/provider_registry.py, packages/ref/src/ref/solver.py, packages/ref/tests/unit/cli/test_root.py, packages/ref/tests/unit/test_solver.py, pyproject.toml, uv.lock
Extend the solver in preparation for adding the information for the requirement for a metric.
This adds an adapter layer for determining what providers are available. Some magic might be needed there to deal with the fact that the Metric classes may not be directly available (because the ref package is installed out of process).
Still needs in follow up PRs
* Metric Run tables
* The ability to check if a metric needs to be run
* #15 
* Loading metrics from other packages
=> feat: Extend the solver

changelog/35.fix.md, packages/ref-core/tests/unit/test_datasets.py, packages/ref/src/ref/datasets/cmip6.py, packages/ref/tests/unit/datasets/test_cmip6/cmip6_catalog_db.yml, packages/ref/tests/unit/datasets/test_cmip6/cmip6_catalog_local.yml, packages/ref/tests/unit/test_solver.py
Adds the version field to the instance_id. 
This makes sure that the hash will change if new versions of datasets become available.
=> fix: Add version to the instance_id

changelog/36.feature.md, packages/ref/src/ref/cli/datasets.py, packages/ref/src/ref/datasets/__init__.py, packages/ref/src/ref/datasets/base.py, packages/ref/src/ref/datasets/cmip6.py, packages/ref/tests/unit/datasets/test_cmip6.py, packages/ref/tests/unit/datasets/test_datasets.py
Rework how we log messages from validation errors.
I managed to import ~2k tas datasets and got some informative log messages when things went wrong. As expected there were lots of inconsistencies and this is only checking that the files in a dataset all have the same metadata, rather than them being correct.
Fixes #34
=> feat: Fixes from ingesting more datasets

changelog/41.trivial.md, conftest.py, packages/ref/tests/unit/cli/test_config.py, packages/ref/tests/unit/cli/test_datasets.py, packages/ref/tests/unit/cli/test_root.py, packages/ref/tests/unit/cli/test_solve.py, tests/integration/test_solve.py
Adds the `invoke_cli` pytest fixture to provide a consistent interface for running CLI tests. 
This fixture handles failures gracefully and provides the context needed for debuggins
=> Add a fixture for running and asserting the results from the CLI

.github/workflows/ci.yaml, .pre-commit-config.yaml, changelog/52.trivial.md
=> Add mypy pre-commit hook

changelog/73.fix.md, docs/gen_doc_stubs.py, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/example.py, packages/ref/src/cmip_ref/provider_registry.py, pyproject.toml, uv.lock
Realized that I had missed some things needed for full integration.
=> missing integration stuff

changelog/74.feature.md, packages/ref-metrics-ilamb/pyproject.toml, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/__init__.py, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/example.py, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/registry.txt, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/standard.py, packages/ref-metrics-ilamb/tests/unit/test_metrics.py, packages/ref-metrics-ilamb/tests/unit/test_provider.py, uv.lock
Adds the ILAMBStandard Metric to the ILAMB provider that runs our standard  analysis. A few comments:
- ILAMB works in 2 phases. The first of those operates on all pairs of (reference_data, model output) for any given variable. This generates some intermediate files containing scalars we want to show (errors and scores, etc) as well as things we want to plot (netcdf file). 
- In a second phase, we take all this intermediate data and now can compute plot limits and make plots/generate html.
- For now, I have lumped phase 1 and 2 in the same Metric.run(). 
- ILAMB specific reference data has been added as a DataCollection via a pooch registry. This already addresses #69.
- For the moment, this will only perform the bias component of the analysis. Need to expand ilamb3 once this interface is …
=> Add ILAMB standard analysis

changelog/82.fix.md, conftest.py, packages/ref/src/cmip_ref/constants.py, packages/ref/tests/unit/test_config.py
Reverts back to use `ref.toml` as the name of the configuration file as per the docs. This was missed in the refactor to the new package names #53 .
=> fix: Make config name consistent

changelog/86.feature.md, docker-compose.yaml, packages/ref-celery/README.md, packages/ref-celery/src/cmip_ref_celery/cli.py, packages/ref-celery/tests/unit/test_cli.py, packages/ref/src/cmip_ref/cli/__init__.py, packages/ref/src/cmip_ref/config.py, packages/ref/tests/unit/cli/test_root.py
Optionally adds the celery CLI commands into the ref CLI.
This is useful in the docker container as the default entrypoint is the REF CLI and any additional commands are passed to this CLIi.e. running `docker run ref celery start-worker` would run the `ref` image with `celery start-worker` which is equivalent to running `uv run ref celery start-worker` locally. 
The alternative is to change the entrypoint in the docker-compose file, but that isn't as clean. Nor is adding the celery commands to the `ref` package. This has a better separation of concerns.
=> Integrate the celery CLI into the ref cli

Makefile, changelog/103.improvement.md, conftest.py, packages/ref-core/src/cmip_ref_core/constraints.py, packages/ref-metrics-example/src/cmip_ref_metrics_example/example.py, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/example.py, packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/example.py, packages/ref/conftest.py, packages/ref/src/cmip_ref/datasets/cmip6.py, pyproject.toml
* Cleans up the a bunch of warnings about the time decoding from newer versions of xarray
* Speeding up the test suite by marking some fixures as session scoped and caching the seeded db for reuse
* Adds a `make test-quick` to run the test suite using the root package rather than targetting each descrete packages
All in all this made the test suite runtime go from 45s to 30 for the full test suite (`make test`) and 9.5s for the quick test suite (`make test-quick`).
=> Speed up tests and clean up some warnings

.env.example, .github/workflows/bump.yaml, .github/workflows/deploy.yaml, Makefile, README.md, changelog/119.docs.md, docker-compose.yaml, docs/changelog.md, docs/development.md, docs/installation.md, docs/roadmap.md, mkdocs.yml, packages/ref/src/cmip_ref/testing.py, tests/test-data/README.md, towncrier.toml
This doesn't change the package names, but fixes up the rest of the documentation.
=> Fix CMIP-REF -> Climate-REF renaming

Makefile, changelog/155.improvement.md, docs/development.md
Temporarily, you still need reference data not in obs4mips to run ilamb for development. Add a makefile command for that and a corresponding section in the docs.
=> feat: add makefile command to download ilamb ref data

changelog/160.improvement.md, docs/hackathon.md, packages/ref-core/src/cmip_ref_core/providers.py, packages/ref-core/tests/unit/test_providers.py, packages/ref/src/cmip_ref/cli/providers.py
Improvements:
- Do not mention conda as a requirement on the Hackathon page
- Drop plugin version number in environment name because the environment may not change between releases
- Avoid calling micromamba update as this may not work for everyone
- Print out location of environments even when not installed
=> Improve conda environment installation

changelog/182.trivial.md, docs/hackathon.md
Small tweaks so that the hackathon page can also be used for pre-alpha post-hackathon onboarding
=> docs: update hackathon page to better fit for pre-alpha onboarding

.github/workflows/containers.yaml, changelog/156.feature.md
Added Github Action to build and publish REF container to Github Container Registry
=> feat: Build and publish Docker containers in CI

changelog/174.fix.md, packages/ref/src/cmip_ref/datasets/obs4mips.py, packages/ref/tests/unit/datasets/test_obs4mips.py
These changes resolve #153. Warnings are logged when the REF is trying to ingest non-obs4mips compliant data, and if there were no obs4mips-compliant datasets ingested it throws an exception.
=> Throws exception if no obs4mips-compliant datasets found during ingestion

.github/workflows/ci-integration.yaml, .github/workflows/ci.yaml, Makefile, changelog/187.improvement.md, conftest.py, packages/ref-celery/pyproject.toml, packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/standard.py, packages/ref-metrics-pmp/tests/unit/test_variability_modes.py, packages/ref/tests/unit/cli/test_datasets.py, pyproject.toml, ruff.toml, tests/integration/test_ar7_ft.py, tests/integration/test_celery.py
Add an integration test for the AR7 FT setup. This adds a workflow which is run nightly.
The results from the test suite are now archived to enable debugging if the suite fails
PMP is currently failing due to missing data so is ignored.
=> test: Add an integration test for the AR7 FT metric providers

changelog/203.improvement.md, packages/ref-core/tests/unit/test_metrics.py, packages/ref/src/cmip_ref/_config_helpers.py, packages/ref/src/cmip_ref/cli/datasets.py, ruff.toml
Adds a nicer error message when running `ref datasets list` with the `--column` argument. If a column is specified that is not available in the dataframe, a list of available columns will be shown.
=> Nicer error message when specifying wrong columns in `ref datasets list`

changelog/209.fix.md, packages/ref-core/src/cmip_ref_core/metrics.py, packages/ref-core/tests/unit/test_metrics.py
For the TCRE metric #208, I need variables `"tas"` and `"fco2antt"` from the `"esm-1pctCO2"` experiment and variable `"tas"` from the `"esm-piControl"` experiment. Therefore I wrote the following filters:
```
FacetFilter(
facets={
"variable_id": ("tas", "fco2antt"),
"frequency": "mon",
"experiment_id": ("esm-1pctCO2", "esm-piControl"),
},
),
FacetFilter(
facets={
"variable_id": "fco2antt",
"experiment_id": "esm-piControl",
},
keep=False,
),
```
The first filter selects all files with `"variable_id"` `"tas"` and `"fco2antt"` from both experiments and the second filter then excludes files with `"variable_id"` `"fco2antt"` from the `"esm-piControl"` experiment.
The implementation here makes the above filters work as expected.
=> Match all facet values when using `FacetFilter` with `keep=False`

changelog/183.feature.md, packages/ref-core/src/cmip_ref_core/exceptions.py, packages/ref-core/src/cmip_ref_core/pycmec/controlled_vocabulary.py, packages/ref-core/src/cmip_ref_core/pycmec/metric.py, packages/ref-core/tests/unit/pycmec/cmec_testdata/cv_sample.yaml, packages/ref-core/tests/unit/pycmec/conftest.py, packages/ref-core/tests/unit/pycmec/test_cmec_metric.py, packages/ref-core/tests/unit/pycmec/test_controlled_vocabulary.py
Adds the basic framework for a controlled vocabulary for metric values and their dimensions. 
This is still a prototype, but it provides an example about how we could capture information about the dimensions we will use in the metric bundles.
The CMIP cvs are generally JSON files, one for each controlled dimension. They capture additional metadata about each of the controlled values. We need to support the definition of all permitted dimensions in addition to the controlled ones which has led to more structured schema as to also capture that information. Yaml was a more readable alternative imho 
If the cv grows to where it is difficult to follow we can split it out into different dimensions as well. The ref needs different information compared to the CMIP cvs so they couldn't be used …
=> feat: Add basic support for a controlled vocabulary

changelog/230.improvement.md, packages/ref-core/src/cmip_ref_core/metrics.py, packages/ref-core/tests/unit/test_metrics.py, packages/ref/src/cmip_ref/config.py, packages/ref/tests/unit/cli/test_root.py, packages/ref/tests/unit/test_config.py
Ensures that the paths in the config object are always absolute.
This makes it easier to check if we have a path relative to an output directory or a fully resolved path.
=> Ensure that the paths are always absolute

changelog/236.feature.md, packages/ref-core/src/cmip_ref_core/providers.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/__init__.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/recipe.py, packages/ref/src/cmip_ref/cli/providers.py
Add an option to install a development version of a metrics package. To add a development version of the metrics package used by a provider, instantiate the provider with a `repo` and `tag_or_commit` arguments, e.g.:
https://github.com/bouweandela/climate-ref/blob/38547119fad35a2079a9fd2653d02527d7ed45e5/packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/__init__.py#L11-L15
=> Add option to install a development version of a metrics package

.github/workflows/ci.yaml, changelog/266.feature.md, changelog/267.fix.md, docs/how-to-guides/metric-dataset-selection.py, packages/ref-core/src/cmip_ref_core/dataset_registry.py, packages/ref-core/src/cmip_ref_core/datasets.py, packages/ref-core/src/cmip_ref_core/metrics.py, packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/annual_cycle.py, packages/ref-metrics-pmp/tests/unit/test_annual_cycle.py, packages/ref/src/cmip_ref/solver.py, packages/ref/tests/unit/test_solver.py
Support multiple data requirements, either a list of data requirements or a list of lists of data requirements where each inner list is processed independently.
These different sets of data requirements can have different group bys and different filters.
=> Support multiple sets of data requirements

changelog/263.breaking.md, changelog/266.feature.md, changelog/268.fix.md, docs/how-to-guides/metric-dataset-selection.py, packages/ref-core/src/cmip_ref_core/datasets.py, packages/ref-core/src/cmip_ref_core/metrics.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/climate_at_global_warming_levels.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/ecs.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/example.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/sea_ice_area_seasonal_cycle.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcr.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcre.py, packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/zec.py, packages/ref-metrics-esmvaltool/tests/unit/test_metrics.py, packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/annual_cycle.py, packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/variability_modes.py, packages/ref-metrics-pmp/tests/unit/test_annual_cycle.py, packages/ref/src/cmip_ref/solver.py, packages/ref/tests/unit/test_solver.py
PMP annual cycle output JSON file includes `CaldendarMonth` key and its value is a list. To comply with CMEC, renamed the `CaldendarMonth` to `CaldendarMonth-01` ~ `CaldendarMonth-12` and assigned their value individually, so list is not used as value in the JSON.
=> PMP annual cycle: `CaldendarMonth`

Makefile, changelog/269.docs.md, docs/gen_doc_stubs.py, packages/ref-celery/README.md, packages/ref-core/README.md, packages/ref-metrics-esmvaltool/README.md, packages/ref-metrics-ilamb/README.md, packages/ref-metrics-pmp/README.md, packages/ref/README.md, packages/ref/pyproject.toml, uv.lock
Adds a deprecation notice to each Readme file on pypi with instructions about migrating. I will then do a final release using the old package names and then refactor to follow the new package names.
This no longer publishes the example package as it isn't needed now that we have actual providers.
=> Add deprecation notice in package README's

changelog/281.fix.md, packages/climate-ref-pmp/pyproject.toml, packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/annual_cycle.py, packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/variability_modes.py, packages/climate-ref-pmp/src/climate_ref_pmp/pmp_driver.py, packages/climate-ref-pmp/tests/unit/test_annual_cycle.py, packages/climate-ref-pmp/tests/unit/test_pmp_driver.py, packages/climate-ref-pmp/tests/unit/test_variability_modes.py, uv.lock
This is a workaround for MPICH failures on macOS.
This also removes a direct dependency on the pcmdi_metric source on GitHub (since pcmdi_metrics doesn't have a release on PyPi). Instead the driver scripts in the conda installation are used.
=> Set the FI_PROVIDER environment variable

changelog/284.fix.md, packages/climate-ref-core/src/climate_ref_core/pycmec/metric.py, packages/climate-ref-core/tests/unit/pycmec/cmec_testdata/test_metric_json_schema.yml, packages/climate-ref-core/tests/unit/pycmec/test_cmec_metric.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/climate_at_global_warming_levels.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/cloud_radiative_effects.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/example.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/sea_ice_area_seasonal_cycle.py, tests/test-data/regression/esmvaltool/climate-at-global-warming-levels/cmip6_ssp126/diagnostic.json, tests/test-data/regression/esmvaltool/cloud-radiative-effects/cmip6_gn_r1i1p1f1_ACCESS-ESM1-5/diagnostic.json, tests/test-data/regression/esmvaltool/global-mean-timeseries/cmip6_CMIP6.C4MIP CDRMIP.CSIRO.ACCESS-ESM1-5.esm-1pct-brch-1000PgC.r1i1p1f1.Amon.tas.gn.v20191206/diagnostic.json, tests/test-data/regression/esmvaltool/sea-ice-area-seasonal-cycle/cmip6_CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.SImon.siconc.gn.v20200817/diagnostic.json
Update the default metric bundle to be empty.
Fixed the validation of empty bundles
=> fix: Allow empty metric bundles

changelog/292.improvement.md, docs/getting_started.md, packages/climate-ref-core/src/climate_ref_core/executor.py, packages/climate-ref-core/src/climate_ref_core/pycmec/metric.py, packages/climate-ref/src/climate_ref/cli/__init__.py, packages/climate-ref/src/climate_ref/executor/local.py, packages/climate-ref/tests/unit/cli/test_root.py
Changes the default log level of the CLI to INFO along with fixing a few minor logging issues
`--quiet` and `--verbose` can be used to easily change the log level
=> Update the default log level of the CLI to info

changelog/299.improvement.md, changelog/301.improvement.md, packages/climate-ref/src/climate_ref/config.py, packages/climate-ref/src/climate_ref/database.py, packages/climate-ref/tests/unit/test_config.py, packages/climate-ref/tests/unit/test_database.py
Added automatic backup of SQLite database files before running migrations.
Backups are stored in a `backups` directory adjacent to the database file and are named with timestamps.
The number of backups to retain can be configured via the `db.max_backups` setting in the database configuration,
with a default of 5 backups.
=> feat: Add backups for the database

changelog/349.improvement.md, packages/climate-ref/src/climate_ref/config.py, packages/climate-ref/tests/unit/test_config.py
Allow arbitrary environment variables to be used in paths in the configuration file. This feature was requested at the feedback session today.
=> Allow arbitrary environment variables to be used in paths in the configuration file

changelog/384.fix.md, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/base.py
When switching from ruamel.yaml to pyyaml in #378, I introduced a bug that caused the order of preprocessing steps to be discarded. This has broken diagnostics enso-basic-climatology, enso-characteristics, and transient-climate-response-emissions.
=> Fix bug in writing ESMValTool recipes that loses order of preprocessing steps

changelog/392.feature.md, packages/climate-ref-core/src/climate_ref_core/providers.py, packages/climate-ref-core/tests/unit/test_providers.py, packages/climate-ref-pmp/src/climate_ref_pmp/__init__.py, packages/climate-ref-pmp/src/climate_ref_pmp/pmp_driver.py
This should fix the crash of PMP diagnostics when `conda` is not installed, once the version of PMP used by the ref has been updated to include https://github.com/PCMDI/pcmdi_metrics/pull/1316.
=> Specify environment variables when running PMP diagnostic

changelog/416.breaking.md, packages/climate-ref-core/src/climate_ref_core/constraints.py, packages/climate-ref-core/tests/unit/test_constraints.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/climate_at_global_warming_levels.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/climate_drivers_for_fire.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/cloud_radiative_effects.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/cloud_scatterplots.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/ecs.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/enso.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/regional_historical_changes.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/sea_ice_sensitivity.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/tcr.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/tcre.py, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/zec.py
Replace all constraints that had a boolean decision to keep or discard the entire group with a more fine-grained decision that filters out just those subgroups that do not match the constraint.
Closes #415 
=> Use constraints that filter the group instead of discard the full group

changelog/427.fix.md, packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/cloud_scatterplots.py
=> Avoid selecting the areacella variable when filling the recipe for cloud scatterplots
