Climate-REF/climate-ref

.github/workflows/ci.yaml
.gitignore
Makefile
changelog/8.feature.md
packages/ref-core/pyproject.toml
packages/ref-core/src/ref_core/exceptions.py
packages/ref/README.md
packages/ref/pyproject.toml
packages/ref/src/ref/__init__.py
packages/ref/src/ref/cli/__init__.py
packages/ref/src/ref/cli/config.py
packages/ref/src/ref/cli/sync.py
packages/ref/src/ref/config.py
packages/ref/src/ref/constants.py
packages/ref/src/ref/env.py
packages/ref/tests/conftest.py
packages/ref/tests/unit/cli/test_config.py
packages/ref/tests/unit/test_config.py
packages/ref/tests/unit/test_version.py
pyproject.toml
stubs/environs/__init__.pyi
uv.lock

Adds the `ref` package which will contain the database tracking which jobs have been run and their status

feat: Add a ref package

---

.bumpversion.toml
.github/release_template.md
.github/workflows/bump.yaml
.github/workflows/deploy.yaml
.github/workflows/release.yaml
changelog/20.improvement.md
docs/development.md
pyproject.toml
scripts/changelog-to-release-template.py
uv.lock

Adds a bump, release and deploy flow for the package

chore: Add workflows for publishing/deploying

---

changelog/24.feature.md
packages/ref/conftest.py
packages/ref/src/ref/cli/ingest.py
packages/ref/src/ref/cli/solve.py
packages/ref/src/ref/datasets/base.py
packages/ref/src/ref/datasets/cmip6.py
packages/ref/src/ref/solver.py
packages/ref/tests/unit/cli/test_ingest.py
packages/ref/tests/unit/datasets/test_cmip6.py
packages/ref/tests/unit/datasets/test_cmip6/cmip6_catalog.yml
packages/ref/tests/unit/datasets/test_cmip6/cmip6_catalog_db.yml
packages/ref/tests/unit/datasets/test_cmip6/cmip6_catalog_local.yml
packages/ref/tests/unit/datasets/test_datasets.py
pyproject.toml
uv.lock

Load a data catalog from the database.
This will be serialised and made available to the executed metric

Extract datasets from the db as a catalog

---

changelog/29.feature.md
conftest.py
docs/how-to-guides/running-metrics-locally.py
packages/ref-core/src/ref_core/datasets.py
packages/ref-core/src/ref_core/exceptions.py
packages/ref-core/src/ref_core/executor/__init__.py
packages/ref-core/src/ref_core/executor/local.py
packages/ref-core/src/ref_core/metrics.py
packages/ref-core/src/ref_core/providers.py
packages/ref-core/tests/conftest.py
packages/ref-core/tests/unit/test_datasets.py
packages/ref-core/tests/unit/test_executor.py
packages/ref-core/tests/unit/test_metrics.py
packages/ref-metrics-example/src/ref_metrics_example/__init__.py
packages/ref-metrics-example/src/ref_metrics_example/example.py
packages/ref-metrics-example/tests/unit/test_metrics.py
packages/ref-metrics-example/tests/unit/test_provider.py
packages/ref/conftest.py
packages/ref/src/ref/cli/ingest.py
packages/ref/src/ref/datasets/cmip6.py
packages/ref/src/ref/datasets/utils.py
packages/ref/src/ref/solver.py
packages/ref/tests/unit/cli/test_ingest.py
packages/ref/tests/unit/datasets/test_utils.py
packages/ref/tests/unit/test_solver.py

Link up solver with executing metrics

---

.github/workflows/ci.yaml
.readthedocs.yaml
README.md
changelog/30.breaking.md
changelog/30.feature.md
docs/how-to-guides/dataset-selection.py
docs/how-to-guides/ingest-datasets.md
docs/how-to-guides/running-metrics-locally.py
mkdocs.yml
packages/ref/alembic/env.py
packages/ref/conftest.py
packages/ref/src/ref/cli/__init__.py
packages/ref/src/ref/cli/_logging.py
packages/ref/src/ref/cli/config.py
packages/ref/src/ref/cli/datasets.py
packages/ref/src/ref/cli/solve.py
packages/ref/src/ref/datasets/base.py
packages/ref/src/ref/datasets/cmip6.py
packages/ref/tests/unit/cli/test_config.py
packages/ref/tests/unit/cli/test_datasets.py
packages/ref/tests/unit/cli/test_root.py
packages/ref/tests/unit/datasets/test_cmip6.py

* Moves the `ref ingest` cli command to `ref datasets ingest`
* Adds `ref datasets list` and `ref datasets list-columns`

Move ingest to datasets ingest

---

changelog/39.feature.md
packages/ref-core/src/ref_core/datasets.py
packages/ref/src/ref/datasets/cmip6.py
packages/ref/src/ref/models/__init__.py
packages/ref/src/ref/models/metric_execution.py
packages/ref/src/ref/solver.py
tests/integration/test_solve.py

Adds dataset information to the database

Register datasets/execution links into the database

---

changelog/42.fix.md
packages/ref/src/ref/datasets/cmip6.py
packages/ref/tests/unit/datasets/test_cmip6.py

Handle none values in branch times

---

.github/workflows/ci.yaml
changelog/44.trivial.md

fix: Update codecov version

---

.github/workflows/ci.yaml
Makefile
changelog/40.feature.md
docs/gen_doc_stubs.py
packages/ref-metrics-esmvaltool/README.md
packages/ref-metrics-esmvaltool/pyproject.toml
packages/ref-metrics-esmvaltool/src/ref_metrics_esmvaltool/__init__.py
packages/ref-metrics-esmvaltool/src/ref_metrics_esmvaltool/example.py
packages/ref-metrics-esmvaltool/src/ref_metrics_esmvaltool/recipe.py
packages/ref-metrics-esmvaltool/src/ref_metrics_esmvaltool/recipes.txt
packages/ref-metrics-esmvaltool/tests/unit/test_metrics.py
packages/ref-metrics-esmvaltool/tests/unit/test_provider.py
packages/ref/src/ref/provider_registry.py
packages/ref/tests/unit/cli/test_datasets.py
packages/ref/tests/unit/test_solver.py
pyproject.toml
tests/integration/test_solve.py
uv.lock

Add an example ESMValTool metric. First step towards #32.

Add ESMValTool example metric

---

.bumpversion.toml
.github/actions/setup/action.yml
.pre-commit-config.yaml
changelog/55.trivial.md
packages/ref-core/tests/unit/test_version.py
packages/ref-metrics-esmvaltool/tests/unit/test_provider.py
packages/ref-metrics-example/tests/unit/test_provider.py
packages/ref/tests/unit/test_version.py
uv.lock

chore: Update lockfile as part of the precommit step

---

.github/actions/setup/action.yml
.github/workflows/deploy.yaml
changelog/56.trivial.md
docs/changelog.md

fix: Attempt a fix on the deploy action

---

README.md
changelog/61.docs.md
docs/changelog.md
docs/development.md
scripts/changelog-to-release-template.py
towncrier.toml

Update the package name in the changelog

fix: Correct the changelog to use the _ separated name

---

changelog/62.feature.md
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/__init__.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/__init__.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcr.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/recipes.txt
packages/ref-metrics-esmvaltool/tests/unit/metrics/input_files_tcr.json
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_tcr.py
packages/ref-metrics-esmvaltool/tests/unit/test_provider.py

Add ESMValTool Transient Climate Response recipe

---

changelog/89.breaking.md
changelog/89.improvement.md
mkdocs.yml
packages/ref/src/cmip_ref/config.py
packages/ref/src/cmip_ref/executor/local.py
packages/ref/tests/unit/cli/test_root.py
packages/ref/tests/unit/test_config.py

This better aligns with our dcumentation

rename tmp path to scratch

---

.pre-commit-config.yaml
changelog/98.docs.md
docs/background/architecture.md
docs/getting_started.md
docs/roadmap.md
mkdocs.yml
pyproject.toml
uv.lock

This also adds the ability to view mermaid diagrams which are needed by the celery executor as well

Adds a roadmap to the docs

---

.env.example
changelog/92.improvement.md
docker-compose.yaml
docs/configuration.md
docs/how-to-guides/running-metrics-locally.py
mypy_plugin.py
packages/ref/src/cmip_ref/_config_helpers.py
packages/ref/src/cmip_ref/config.py
packages/ref/src/cmip_ref/database.py
packages/ref/tests/unit/test_config.py
packages/ref/tests/unit/test_database.py
pyproject.toml
uv.lock

This puts the environment variable overrides for configuration values beside the configuration. This should make it clearer what environment variables are used where.

Enable environment variables to override configuration values

---

changelog/99.improvement.md
conftest.py
docs/how-to-guides/running-metrics-locally.py
packages/ref-core/src/cmip_ref_core/metrics.py
packages/ref-core/src/cmip_ref_core/pycmec/metric.py
packages/ref-core/src/cmip_ref_core/pycmec/output.py
packages/ref-core/tests/unit/test_metrics.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/base.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/ecs.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/example.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcr.py
packages/ref-metrics-esmvaltool/tests/unit/test_metrics.py
packages/ref-metrics-example/src/cmip_ref_metrics_example/example.py
packages/ref-metrics-example/tests/unit/test_metrics.py
packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/example.py
packages/ref-metrics-ilamb/src/cmip_ref_metrics_ilamb/standard.py
packages/ref-metrics-ilamb/tests/unit/test_metrics.py
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/example.py
packages/ref-metrics-pmp/tests/unit/test_metrics.py
packages/ref/tests/unit/test_executor.py

- changed pycmec's dump_to_json method to accept pathlib.Path
- modified metrics.py in ref-core to validate results using pycmec models
- validated results by pycmec in example.py
- changed tests in ref, ref-core and ref-metrics-example to reflect changes

initial pycmec integration in ref

---

changelog/120.docs.md
docs/hackathon.md

Adds a basic overview page for hackathon attendees

Adds a page for Hackathon attendees

---

.env.example
.github/workflows/deploy.yaml
NOTICE
README.md
changelog/122.docs.md
docs/changelog.md
docs/development.md
docs/installation.md
docs/roadmap.md
mkdocs.yml
packages/ref/Dockerfile
packages/ref/src/cmip_ref/testing.py
tests/test-data/README.md
towncrier.toml

Fix error in the case of the Climate-REF GH group

---

README.md
changelog/126.docs.md
docs/development.md

Very small fixes, but probably good to get them onto the homepage before the hackathon.

docs: fix getting started data ingestion

---

packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/pmp_driver.py
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/variability_modes.py
packages/ref/src/cmip_ref/solver.py

PMP clean up

---

packages/ref-metrics-pmp/tests/unit/test_pmp_driver.py

fix some tests to include experiment_id

---

changelog/154.fix.md
conftest.py
packages/ref-metrics-pmp/pyproject.toml
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/pmp_driver.py
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/registry/__init__.py
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/requirements/conda-lock.yml
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/requirements/environment.yml
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/variability_modes.py
packages/ref-metrics-pmp/tests/unit/test_pmp_driver.py
packages/ref-metrics-pmp/tests/unit/test_variability_modes.py
packages/ref/src/cmip_ref/solver.py
uv.lock

- `conda` usage inside of PMP (which was to generate provenance info) was turned off to avoid conflict with REF

PMP implementation update

---

changelog/170.fix.md
packages/ref-core/src/cmip_ref_core/metrics.py
packages/ref-core/src/cmip_ref_core/providers.py
packages/ref-core/tests/unit/test_metrics.py
packages/ref/src/cmip_ref/executor/__init__.py
packages/ref/src/cmip_ref/models/metric_execution.py
packages/ref/tests/unit/executor/test_executor.py

fix: Ensure that relative paths are always used

---

.github/workflows/containers.yaml
changelog/184.trivial.md

Move permissions to the top of the job

Hotfix permissions

---

changelog/186.feature.md
packages/ref/src/cmip_ref/cli/solve.py
packages/ref/tests/unit/cli/test_solve.py

Adds a timeout parameter to the solve command

feat: Add a timeout parameter to the solve command

---

changelog/133.fix.md
packages/ref-core/src/cmip_ref_core/pycmec/metric.py
packages/ref-core/tests/unit/pycmec/cmec_testdata/cmec_metric_sample.json
packages/ref-core/tests/unit/pycmec/test_cmec_metric.py
packages/ref-metrics-pmp/src/cmip_ref_metrics_pmp/pmp_driver.py

fix the validation error when 'attributes' value is a dict

---

.github/workflows/containers.yaml
changelog/207.ci.md

Disable pushing container images from forks

---

changelog/210.improvement.md
packages/ref/src/cmip_ref/cli/_utils.py
packages/ref/src/cmip_ref/cli/datasets.py

This removes duplicate entries when listing dataframes using the CLI. For example:
```
$ ref datasets list --column variable_id
variable_id  
───────────── 
tas          
areacella    
fco2antt     
areacello    
tos          
rlut         
rsdt         
rsut         
siconc       
```
instead of
```
$ ref datasets list --column variable_id
variable_id  
───────────── 
tas          
areacella    
fco2antt     
tas          
tas          
areacella    
tas          
areacella    
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
areacello    
tos          
rlut         
rsdt         
rsut         
tas …
```

Do not list duplicate entries from the CLI

---

changelog/235.improvement.md
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/base.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/ecs.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/example.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcr.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/tcre.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/metrics/zec.py
packages/ref-metrics-esmvaltool/src/cmip_ref_metrics_esmvaltool/types.py
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_base.py
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_ecs.py
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_tcr.py
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_tcre.py
packages/ref-metrics-esmvaltool/tests/unit/metrics/test_zec.py
packages/ref-metrics-esmvaltool/tests/unit/test_metrics.py

Update ESMValTool metric and output bundles

---

changelog/259.fix.md
packages/ref-metrics-pmp/tests/integration/test_variability_modes.py
packages/ref-metrics-pmp/tests/unit/test_pmp_driver.py
packages/ref-metrics-pmp/tests/unit/test_variability_modes.py

Mark broken tests as xfail

---

.github/workflows/ci-integration.yaml
changelog/265.fix.md
tests/integration/test_cmip7_aft.py

Adds ESMValTool data to the integration test

Fix integration test

---

.github/workflows/ci.yaml
changelog/267.fix.md
packages/ref-core/src/cmip_ref_core/dataset_registry.py

Retry downloads if they fail

---

changelog/276.feature.md
packages/climate-ref-core/src/climate_ref_core/datasets.py
packages/climate-ref-core/src/climate_ref_core/pycmec/metric.py
packages/climate-ref-core/tests/unit/test_datasets.py
packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/annual_cycle.py
packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/variability_modes.py
packages/climate-ref-pmp/tests/unit/test_annual_cycle.py
packages/climate-ref/src/climate_ref/executor/__init__.py
packages/climate-ref/src/climate_ref/models/metric_value.py
packages/climate-ref/src/climate_ref/solver.py
packages/climate-ref/tests/unit/test_solver.py
ruff.toml

* Relaxes the assert ruff check
* Adds a `selector_dict` function
* Ensures that selectors are sorted
* General cleanup/renaming

Ensure that selectors are sorted

---

.bumpversion.toml
.pre-commit-config.yaml
CITATION.cff
changelog/283.improvement.md

Add citation file

---

changelog/288.fix.md
docker-compose.yaml
docs/how-to-guides/running-diagnostics-locally.py
packages/climate-ref-celery/src/climate_ref_celery/cli.py
packages/climate-ref-celery/src/climate_ref_celery/tasks.py
packages/climate-ref-celery/tests/unit/test_cli.py
packages/climate-ref-celery/tests/unit/test_tasks.py
packages/climate-ref-core/src/climate_ref_core/executor.py
packages/climate-ref-core/src/climate_ref_core/logging.py
packages/climate-ref-core/tests/unit/test_logging.py
packages/climate-ref-core/tests/unit/test_providers.py
packages/climate-ref/src/climate_ref/cli/__init__.py
packages/climate-ref/src/climate_ref/cli/datasets.py
packages/climate-ref/src/climate_ref/cli/executions.py
packages/climate-ref/src/climate_ref/cli/providers.py
packages/climate-ref/src/climate_ref/cli/solve.py
packages/climate-ref/src/climate_ref/config.py
packages/climate-ref/src/climate_ref/constants.py
packages/climate-ref/src/climate_ref/database.py
packages/climate-ref/src/climate_ref/datasets/base.py
packages/climate-ref/src/climate_ref/executor/local.py
packages/climate-ref/src/climate_ref/executor/result_handling.py
packages/climate-ref/src/climate_ref/executor/synchronous.py
packages/climate-ref/src/climate_ref/provider_registry.py
packages/climate-ref/src/climate_ref/solver.py
packages/climate-ref/tests/unit/test_solver.py
scripts/initialise-docker.sh

Rework where we start database transactions to ensure changes are persisted to the database and aren't rolled back if a solve times out. This was causing issues for the celery worker which run in a different process.

Change transaction management during a solve

---

changelog/297.fix.md
packages/climate-ref/src/climate_ref/migrations/env.py

fix: Wrap optional dependency in import guard

---

.github/workflows/ci.yaml
.github/workflows/install-pypi.yaml
changelog/306.improvement.md
packages/climate-ref-core/pyproject.toml
scripts/test-install.py
uv.lock

Checks that the PyPi releases are installable

Add pypi install check

---

.github/workflows/install-pypi.yaml
changelog/307.fix.md
packages/climate-ref-celery/pyproject.toml
packages/climate-ref-core/pyproject.toml
uv.lock

Added dependency on 
* environs
* ruamel.yaml

fix: Add additional dependencies to core library

---

.github/workflows/ci.yaml
.github/workflows/install-pypi.yaml
Makefile
changelog/312.docs.md
docs/development.md
docs/hackathon.md
docs/installation.md
docs/introduction/basic-concepts.md
mkdocs.yml
packages/climate-ref-celery/pyproject.toml
packages/climate-ref-core/pyproject.toml
packages/climate-ref-esmvaltool/pyproject.toml
packages/climate-ref-example/pyproject.toml
packages/climate-ref-ilamb/pyproject.toml
packages/climate-ref-pmp/pyproject.toml
packages/climate-ref/pyproject.toml
pyproject.toml
tests/integration/test_cmip7_aft.py
uv.lock

This cleans up the expected results from the aft integration test

Cleanup aft regression test

---

.github/ISSUE_TEMPLATE/bug.md
changelog/323.feature.md
packages/climate-ref-celery/src/climate_ref_celery/app.py
packages/climate-ref-core/src/climate_ref_core/logging.py
packages/climate-ref/src/climate_ref/cli/__init__.py
packages/climate-ref/src/climate_ref/config.py
packages/climate-ref/src/climate_ref/executor/local.py
packages/climate-ref/tests/unit/cli/test_root.py
packages/climate-ref/tests/unit/test_config.py

Adds log files to the logs directory

Write out verbose log files for debugging

---

changelog/335.improvement.md
packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/annual_cycle.py

PMP annual cycle: enable additional variables

---

changelog/337.fix.md
packages/climate-ref-pmp/src/climate_ref_pmp/diagnostics/variability_modes.py

remove keys with their value as none from json to address #329

clean up cmec json for PMP MoV

---

changelog/372.improvement.md
packages/climate-ref-example/src/climate_ref_example/example.py
packages/climate-ref-example/tests/unit/test_metrics.py

Adds additional dimensions to the example output

Increase the dimensionality of the example output

---

changelog/397.improvement.md
docs/roadmap.md
packages/climate-ref-core/src/climate_ref_core/executor.py
packages/climate-ref/src/climate_ref/executor/__init__.py
packages/climate-ref/src/climate_ref/executor/hpc.py
scripts/test-install.py

Provides a better error message when importing the HPCExecutor on Windows

Handle HPCExector on Windows

---

changelog/431.improvement.md
packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/diagnostics/climate_at_global_warming_levels.py
packages/climate-ref-esmvaltool/src/climate_ref_esmvaltool/recipe.py
packages/climate-ref-esmvaltool/tests/unit/diagnostics/recipes/recipe_climate_at_global_warming_levels.yml
packages/climate-ref-esmvaltool/tests/unit/test_diagnostic.py

Improve support for concatenating historical and future experiments in the ESMValTool recipe
Cf. #428 

Improve support for concatenating historical and future experiments in the ESMValTool recipe

---

.vscode/settings.json
changelog/434.feature.md
packages/climate-ref/src/climate_ref/database.py
packages/climate-ref/src/climate_ref/executor/result_handling.py
packages/climate-ref/src/climate_ref/migrations/env.py
packages/climate-ref/src/climate_ref/models/base.py
packages/climate-ref/src/climate_ref/models/diagnostic.py
packages/climate-ref/src/climate_ref/models/execution.py
packages/climate-ref/src/climate_ref/models/metric_value.py
packages/climate-ref/src/climate_ref/models/mixins.py
packages/climate-ref/src/climate_ref/models/provider.py
packages/climate-ref/tests/unit/executor/test_result_handling.py
packages/climate-ref/tests/unit/models/test_metric_execution.py
packages/climate-ref/tests/unit/test_database.py
ruff.toml

Adds the concept of dimensions to an execution output.
This refactors the dimension handling into a common mixin. 
Adding dimensions to the outputs will happen in a follow up

Figure dimensions
